name: 🔧 Other
description: Use this for any other issues. Please do NOT create blank issues
title: "[OTHER] <description>"
body:
  - type: markdown
    attributes:
      value: "# Other issue"
  - type: textarea
    id: issuedescription
    attributes:
      label: Something else you wanna ask me About?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: system
    attributes:
      label: "Device Information"
      description: What system/browser(s) are you seeing the problem on ?
      value: |
          1. OS: [eg. iOS] 
          2. Browser [e.g. chrome, safari]
          3. Version [e.g. 22]
      render: bash
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else I should know about this issue?
    validations:
      required: false
  - type: dropdown
    id: work
    attributes:
      label: Want to contribute ?
      description: Are you interested in working this Issue ?? (Yes/No)
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: false